FROM golang:1.25.5-alpine AS builder 

WORKDIR /app

COPY go.mod go.sum ./ 
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /main_app ./cmd/main/main.go

FROM alpine:latest
COPY --from=builder /main_app /main_app

CMD ["./main_app"]
