events {}

http {
  server {
    listen 80;

    # SPA-РОУТЫ
    location / {
      proxy_pass http://frontend:5173;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # API
    location /api/ {
      proxy_pass http://backend:8080;
    }

    location = /login {
      proxy_pass http://backend:8080;
    }

    location = /login/check {
      proxy_pass http://backend:8080;
    }

    location = /login/verify {
      proxy_pass http://backend:8080;
    }

    location = /logout {
      proxy_pass http://backend:8080;
    }
  }
}
